### PR TITLE
Mobile support

### PR DESCRIPTION
**Pull request by ajrgrubbs**
Test this shit on your iOS device in Safari, please.
Pinch-to-zoom on Chrome not supported because its hard and not that important.

### CODE REVIEW

**Comment by ajrgrubbs** [comment]
Apparently this will only work if your Safari is up-to-date - not sure how available it is on the various iPhone versions. Looking into it currently

**Comment by vforgione** [comment]
Had to install localtunnel for this to work:

```bash
$ npm install -g localtunnel
$ /usr/bin/local/lt --port 8080
```

It spits out a URL you can use on your phone to connect to your machine.

👍

**Comment by adamyala** [comment]
I couldn't get localtunnel to work :(

**Comment by ajrgrubbs** [comment]
Ima merge master into this so we can be sure the latest changes work on devices...

**Comment by csavage1994** [comment]
👍

**Pull request merged**
