### PR TITLE
Fullscreen support

### PR DESCRIPTION
**Pull request by ajrgrubbs**
Interface now takes up entire browser space

### CODE REVIEW

**Comment by adamyala** [comment]
👍

**Comment by csavage1994** [comment]
So I cloned the repo, checked out the fullscreen branch, ran npm install, put my credentials into the `config.js` file, then ran `npm start`. When I go to localhost:8080 the display is in fullscreen, but nothing shows up and I get 2 errors in the console, the first being `d3.js:4846 GET http://localhost:8080/report/393 500 (Internal Server Error)` and the second `(index):18 Uncaught [object ProgressEvent]`

**Comment by ajrgrubbs** [comment]
That was from a bug fixed in a different branch but was never merged into this PR. Should be good now.

**Comment by csavage1994** [comment]
👍

**Pull request merged**
