### PR TITLE
Add a modal that links to other reports.

### PR DESCRIPTION
**Pull request by ajrgrubbs**
Notice the new gear icon at the top right corner

### CODE REVIEW

**Comment by csavage1994** [comment]
I'm getting some `d3.js:4846 GET http://localhost:8080/report/345 500 (Internal Server Error)` and `345:220 Uncaught [object ProgressEvent]` on some of the reports, 310 and 345 are two that I've noticed

**Comment by adamyala** [comment]
👍

**Comment by csavage1994** [comment]
I'm also noticing this error in the terminal on the bad reports `Error fetching report from Interrogated TypeError: Cannot read property 'processes' of undefined`

**Comment by emmanuellyautomated** [comment]
@csavage1994, I did not get those errors...

**Comment by ajrgrubbs** [comment]
@csavage1994 those errors were due to those tasks being unsuccessfully analyzed in Interrogated. Most recent push should have filtered the list down to successfully reported tasks only.

**Comment by csavage1994** [comment]
awesome, looks good now! 👍

**Comment by vforgione** [comment]
👍

**Pull request merged**
