### PR TITLE
Spinner

### PR DESCRIPTION
**Pull request by ajrgrubbs**
A loading spinner appears on page load until graph is ready

### CODE REVIEW

**Comment by adamyala** [comment]
I get
```
SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.
```
In the console, but other than that it looks good.
👍

**Comment by csavage1994** [comment]
I get the same message, other than that 👍

**Comment by ajrgrubbs** [comment]
Good point...might as well fix it. I'll have a new commit up for that soon

**Comment by ajrgrubbs** [comment]
I'm glad I did this - CSS animations don't lock up when javascript is going crazy trying to load huge resources.

**Pull request merged**
