### PR TITLE
Significant performance increase to graph load

### PR DESCRIPTION
**Pull request by ajrgrubbs**
Turns out .getBoundingClientRect() is really expensive.
We now cache the result and explicitly handle cases
where it needs to be refreshed anew.

### CODE REVIEW

**Comment by ajrgrubbs** [comment]
Task 413 is a great one to test this with. Loading time went from over a minute to a couple of seconds

**Comment by csavage1994** [comment]
I get NaNs for the time elapsed for 413

**Comment by adamyala** [comment]
👍

**Comment by ajrgrubbs** [comment]
Ok - the NaNs Colton showed me were caused by empty reports. I don't get enough info from Cuckoo to know when a report will be empty until we actually fetch it, so I patched it by providing a "No data" message, as well as stopping the player from being able to do anything

**Comment by csavage1994** [comment]
👍

**Pull request merged**
