### PR TITLE
Timed draw

### PR DESCRIPTION
**Pull request by ajrgrubbs**
Things to test:
Play/Pause
Clicking on progress bar
dragging around progress bar

### CODE REVIEW

**Comment by csavage1994** [comment]
Not sure if this happened before, but when the opacity of the nodes is set to 0, you can still hover over them and it'll show the information across the bottom. Not sure how big of an issue this is, let me know your thoughts

**Comment by ajrgrubbs** [comment]
Good catch

**Comment by csavage1994** [comment]
👍

**Comment by vforgione** [comment]
👍

**Pull request merged**
