### PR TITLE
Comment catchup

### PR DESCRIPTION
**Pull request by ajrgrubbs**
This is almost completely adding or improving comments.

Three exceptions that are actual code changes:
- The linkFns method lazily sets itself as a property, instead of creating and returning a new object every time. I'd just set it outright, but the ES6 class syntax doesn't allow us to do that. This should give us a performance bump.
- Fixed a bug causing some graph's leaf nodes to get the "red donut" when drawn, which should only appear on a graph's root node.
- Moved the donut path generation to a joined array instead of a templated string.

### CODE REVIEW

**Comment by csavage1994** [comment]
Looks good, however I'm still getting errors with some reports. Report 420 just does nothing reports no data in graph 
image
----------
 and 434 gives
image

**Comment by ajrgrubbs** [comment]
420 is working as intended but could be clearer. the report is literally empty so the graph is also empty. Don't have enough info to filter them out beforehand.

434, from my best guess, is acting that way because some tricksy hacker designed the malware to hijack innocent processes, and it's throwing Vee off. So now I have to figure out how to detect and handle that. THANKS COLTON 👎

**Comment by ajrgrubbs** [comment]
The latest push should address both those issues.
This required changing how we parse reports, so you'll probably want to `rm /tmp/vee_reports/*' before you test this again.

**Comment by adamyala** [comment]
👍

**Comment by vforgione** [comment]
👍 yay comments

**Pull request merged**
